baseURL: "https://furkanolkay.com/"
title: "Furkan Olkay"
paginate: 1000
theme:
  - PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
# disableKinds: ["sitemap"]

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About Me
      url: /about/
      weight: 2
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 4
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 5
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 6
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 7
    - name: Tags
      url: /tags/
      weight: 8
    - identifier: search
      name: üîç
      url: /search/
      weight: 100

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: "Furkan Olkay - Software Engineer & Flutter Developer"
  description: "Software Engineer, Mobile Team Lead, and Flutter Developer. Expert in mobile app development, team leadership, and creating high-performance cross-platform applications. Explore my projects, blog posts, and resources."
  keywords: [Software Engineer, Flutter Developer, Mobile Development, Team Lead, Cross-platform Apps, Dart, Mobile Apps, Software Development, Technology Blog, Programming Tutorials]
  author: Furkan Olkay
  DateFormat: "2024 January 14"
  defaultTheme: light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  enableQuicklink: true

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "/furkanolkay.webp"
    favicon16x16: "/furkanolkay.webp"
    favicon32x32: "/furkanolkay.webp"
    apple_touch_icon: "/furkanolkay.webp"
    safari_pinned_tab: "/furkanolkay.webp"

  label:
    icon: "/logo.svg"
    iconHeight: 100
    iconWidth: 50
    text: " "

  homeInfoParams:
    Title: ":(){ :|:& };:"
    Content: "Software Engineer | Mobile Team Lead | Flutter Developer"

  profileMode:
    enabled: true
    title: "Hi! There"
    subtitle: "Software Engineer | Mobile Team Lead | Flutter Developer"
    imageUrl: "/furkanolkay.webp"
    imageWidth: 200
    imageHeight: 200
    imageTitle: image
    buttons:
      - name: Blog
        url: /blog
        
        

  socialIcons:
    - name: github
      url: "https://github.com/furkanolkay"
    - name: linkedin
      url: "https://linkedin.com/in/furkan-saffet-olkay"
    - name: medium
      url: "https://medium.com/@furkanolkay"
    - name: twitter
      url: "https://twitter.com/furkanolkay"
    - name: instagram
      url: "https://instagram.com/furkan_olkay"    
    - name: email
      url: "mailto:contact@furkanolkay.com"
  #  - name: cv
  #    url: "https://www.google.com"

  cover:
    hidden: false
    hiddenInList: true
    hiddenInSingle: false
    linkFullImages: false

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


